name = "MiniQhull"
uuid = "978d7f02-9e05-4691-894f-ae31a51d76ca"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>", "Victor Sande <vsande@cimne.upc.edu>"]
version = "0.2.1"

[deps]
CMake = "631607c0-34d2-5d66-819e-eb0f9aa2061a"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Qhull_jll = "784f63db-0788-585a-bace-daefebcd302b"

[compat]
CMake = "1.2.0"
Qhull_jll = "v2019.1.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
