name = "MiniQhull"
uuid = "978d7f02-9e05-4691-894f-ae31a51d76ca"
authors = ["Francesc Verdugo <fverdugo@cimne.upc.edu>", "Victor Sande <vsande@cimne.upc.edu>"]
version = "0.3.1"

[deps]
QhullMiniWrapper_jll = "460c41e3-6112-5d7f-b78c-b6823adb3f2d"

[compat]
julia = "1.3"
QhullMiniWrapper_jll = "1"

[extras]
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "StaticArrays"]
